# Generated by Django 2.2.17 on 2021-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_auto_20210110_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='more_information',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='rip_date',
            field=models.DateField(null=True),
        ),
    ]
