# Generated by Django 2.2.17 on 2021-01-10 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('family', '0005_auto_20210110_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='password',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AddField(
            model_name='family',
            name='public_type',
            field=models.CharField(choices=[('Public', 'Công khai'), ('Private', 'Riêng tư')], default='Public', max_length=50),
        ),
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('Approved', 'Đã duyệt'), ('Waiting for approving', 'Đợi duyệt')], default='Waiting for approving', max_length=50),
        ),
        migrations.AlterField(
            model_name='family',
            name='intro',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
