# Generated by Django 2.2.17 on 2021-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20210110_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='intro',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='more_information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='rip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
