# Generated by Django 2.2.17 on 2021-01-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_auto_20210110_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='partner_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
