# Generated by Django 2.2.17 on 2021-01-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0011_auto_20210111_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
