# Generated by Django 2.2.17 on 2021-01-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0012_auto_20210111_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='level',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='member',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='member_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='family.Member'),
        ),
    ]
