# Generated by Django 2.2.17 on 2021-01-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0013_auto_20210111_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
    ]
