# Generated by Django 2.2.17 on 2021-01-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0014_member_is_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_name',
            field=models.CharField(max_length=500, verbose_name='Tên dòng họ'),
        ),
        migrations.AlterField(
            model_name='family',
            name='intro',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Giới thiệu về dòng họ'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parentage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='family.Parentage', verbose_name='Họ'),
        ),
    ]
