# Generated by Django 2.2.17 on 2021-01-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0015_auto_20210112_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Nguyên quán'),
        ),
    ]
